# Generated by Django 4.2.24 on 2025-09-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
