# Generated by Django 4.2.24 on 2025-09-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_students_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("subject", models.CharField(max_length=20)),
            ],
        ),
    ]
