# Generated by Django 4.2.24 on 2025-09-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="joined_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
